import json
import httpx
import asyncio

async def test_backend():
    print("--- STARTING BACKEND INTEGRATION TEST ---")

    async with httpx.AsyncClient() as client:
        # health check
        try:
            resp = await client.get("http://127.0.0.1:8000/health")
            print(f"1. [Health Check] Status: {resp.status_code}")
            print(f"   Response: {resp.json()}")
        except Exception as e:
            print(f"1. [Health Check] Failed: {e}")
            return

        session_id = "test-session-uuid-999"
        payload = {
            "session_id": session_id,
            "round_type": "core_cse",
            "transcript": [
                {
                    "role": "interviewer",
                    "text": "What is MVCC in Database Management Systems?"
                },
                {
                    "role": "candidate",
                    "text": "MVCC stands for Multi-Version Concurrency Control. It allows writers to avoid locking readers by keeping multiple versions of a data row, improving read-write performance."
                }
            ]
        }

        print("\n2. [Gemini Evaluation API] Sending mock transcript to /api/evaluate...")
        try:
            resp = await client.post(
                "http://127.0.0.1:8000/api/evaluate", 
                json=payload,
                timeout=30.0
            )
            print(f"   Status Code: {resp.status_code}")
            if resp.status_code == 200:
                scorecard = resp.json()
                print("   Scorecard successfully generated by Gemini 2.5 Flash:")
                print(f"   - Overall Score: {scorecard.get('overall_score')}/100")
                print(f"   - Verdict: {scorecard.get('hiring_verdict')}")
                print(f"   - Technical Depth Rating: {scorecard.get('metrics', {}).get('technical_depth')}/10")
            else:
                print(f"   Failed: {resp.text}")
                print("   (Ensure your GEMINI_API_KEY is configured in backend/.env)")
                return
        except Exception as e:
            print(f"   API request crashed: {e}")
            return

         # 3. Database Save & Retrieval Test
        print(f"\n3. [MySQL Database] Retrieving Session {session_id} from /api/session/{session_id}...")
        try:
            resp = await client.get(f"http://127.0.0.1:8000/api/session/{session_id}")
            print(f"   Status Code: {resp.status_code}")
            if resp.status_code == 200:
                data = resp.json()
                print("   Success! Session loads from MySQL database cleanly:")
                print(f"   - Retrieved Round Type: {data.get('round_type')}")
                print(f"   - Number of transcript items: {len(data.get('transcript', []))}")
            else:
                print(f"   Failed to retrieve: {resp.text}")
        except Exception as e:
            print(f"   MySQL select request crashed: {e}")
if __name__ == "__main__":
    asyncio.run(test_backend())    